### ISSUE TITLE
VirtualNetworkGateway - The possible value list should be []string

### ISSUE THREAD

**Issue by neil-yechenwei** [tombuildsstuff/kermit#309]
Currently, seems [the possible value list](https://github.com/tombuildsstuff/kermit/blob/df17c857592467c72a2885eb06f6894480722d5e/sdk/network/2022-07-01/network/enums.go#L2426) of the sub properties of [vpnClientIpsecPolicies](https://github.com/Azure/azure-rest-api-specs/blob/663ea6835c33bca216b63f777227db6a459a06b3/specification/network/resource-manager/Microsoft.Network/stable/2023-05-01/virtualNetworkGateway.json#L3038) in VirtualNetworkGateway is not []string. I assume that it should be []string to align with others, right?

**Comment by tombuildsstuff** [comment]
@neil-yechenwei the Network SDK is available in `hashicorp/go-azure-sdk` and so should be used from there instead - can you take a look?

**Comment by tombuildsstuff** [comment]
Similar to #340 since `hashicorp/go-azure-sdk` offers support for the `network` package now, that SDK should be used instead / this isn't something that we're planning to support in this SDK - can you look into using [that SDK instead](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/network)? Thanks!
